### PR TITLE
implements server package

### PR DESCRIPTION
**Pull request by chlbri**
I add a package to handles simple function like state machine.
It's like a state machine without sending events.
The process of action and transitions is like eventless states.

### CODE REVIEW

**Comment by chlbri** [comment]
Also, I added as small function to test a machine

**Review by chlbri — COMMENTED** [review]
Reviewed

**Comment by davidkpiano** [comment]
This was an accidental merge; I reverted the 3 commits.

**Comment by Andarist** [comment]
@chlbri could you perhaps open a discussion thread about your ideas from this PR? We would like to discuss this further but it's not obvious what exact problems are you solving here and how.

**Pull request merged**
