### PR TITLE
Avoid calling `selector` when the snapshot doesn't change

### PR DESCRIPTION
**Pull request by Andarist**
alternative to https://github.com/statelyai/xstate/pull/5080/files

### CODE REVIEW

**Comment by davidkpiano** [comment]
I think there may be a hidden problem with this logic:

```ts
const Component = (props) => {
  const items = useSelector(store, s => {
    return s.context.items.map(item => ({
      ...item,
      isSelected: props.selected === item.id
    }));
  });
}
```

Not the best example but the point is that if we're selecting something that mixes in data outside the snapshot (whether that's best practice or not), we may end up with stale data.

**Review by TkDodo — APPROVED** [review]

**Comment by Andarist** [comment]
That's a fair concern - this is how the React team has implemented' useSyncExternalStoreWithSelector', so I just used their logic here.

**Comment by TkDodo** [comment]
> Not the best example but the point is that if we're selecting something that mixes in data outside the snapshot (whether that's best practice or not), we may end up with stale data.

Ah, I see. closing over values should still work - we could compare the selectorFn for equality but that wouldn't work with inline selectors :/

**Comment by Andarist** [comment]
For context, this is where the original `useSyncExternalStoreWithSelector` is returning early:
https://github.com/facebook/react/blob/8dfbd16fce9077ab4e5fe85a7b86fa7c97a5ae04/packages/use-sync-external-store/src/useSyncExternalStoreWithSelector.js#L83-L86

**Comment by davidkpiano** [comment]
Closing as we went with a different approach

**Pull request closed without merging**
