### PR TITLE
[@xstate/test][@xstate/graph] Fix `getAdjacencyMap` to ignore transitions for events not explicitly passed into the `options.events` 

### PR DESCRIPTION
**Pull request by Silverwolf90**
Wasn't entirely sure what the changeset should be -- this could be considered a breaking change, despite the original behavior being flawed.

Basically, `getAdjacencyMap` would always attempt to find adjacencies for **every** transition. It would first look in the `options.events` to determine the payload, but if none was found, then it would create a payload-less event and use that to find adjacencies.

This is problematic for a couple reasons:
1. We can't assume events can be run without a payload
2. The adjacency map is far more expensive to compute when you only need adjacencies for a subset of events (eg: `getPathFromEvents`

There are a couple threads in discord related to this:

**Expensive adjacency map**
https://discord.com/channels/795785288994652170/809564635614150686/943109510040551424

**getPlanFromEvents tried unwanted transitions**
https://discord.com/channels/795785288994652170/809564635614150686/943823319625519124

Anyway, curious to see what people think!

### CODE REVIEW

**Comment by Silverwolf90** [comment]
Perhaps this will be fixed as part of https://github.com/statelyai/xstate/pull/3036?

**Comment by davidkpiano** [comment]
Hey, just getting back to this! Let's see if we can port some of this logic over to https://github.com/statelyai/xstate/pull/3036

**Comment by Silverwolf90** [comment]
Apologies for the delayed reply!

> Hey, just getting back to this! Let's see if we can port some of this logic over to #3036

Is this not already incorporated? When I tested the PR locally (using `getPlanForEvents`) I didn't notice it to be particularly slow at all where the previous version could take 10+ seconds to build up adjacency map in some of our cases.

**Comment by davidkpiano** [comment]
> Apologies for the delayed reply!
> 
> > Hey, just getting back to this! Let's see if we can port some of this logic over to #3036
> 
> Is this not already incorporated (in some form)? When I tested the PR locally (using `getPlanForEvents`) I didn't notice it to be particularly slow at all where the previous version could take 10+ seconds to build up adjacency map in some of our cases.

Potentially; I'll copy the tests over to verify.

**Comment by davidkpiano** [comment]
This has been fixed in #3036

**Pull request closed without merging**
