### PR TITLE
[Docs] Add new simple Star Wars API search example

### PR DESCRIPTION
**Pull request by Glutnix**

### CODE REVIEW

**Comment by Glutnix** [comment]
I'm really excited to contribute this example to the project :)

**Comment by Andarist** [comment]
This is a cool example! I'm wondering though if we shouldn't keep such examples in this repository - so we can update them when releasing new versions of XState. WDYT @davidkpiano ?

**Comment by davidkpiano** [comment]
Right, this is awesome, but let's make a new `xstate-examples` repository. I'll do that today!

**Comment by Andarist** [comment]
This could also be kept here - in the monorepo. I don't mind creating extra repo for this though.

**Comment by Glutnix** [comment]
Let me know what I need to do :) I’ll merge my example code to wherever :)

**Comment by davidkpiano** [comment]
Hey thanks again for this! We're going to create a similar example and keep it inside the repository.

**Pull request closed without merging**
