### PR TITLE
Initial value as function

### PR DESCRIPTION
**Pull request by danielbrodin**
This PR makes it possible to set the initial state from a function. My use case for this is that I have a parallel machine where I want parts of it to be saved in localStorage, and then initiated with that value. There might be some better way to do this, but currently I am doing this

```js
{
  Volume: {
  initial: 'Initial',
    states: {
      Initial: {
        invoke: {
          src: () =>
            Promise.resolve(
              localStorage.getItem('volume-state') ?? 'Unmuted'
            ),
          onDone: [
            {
              cond: (c, e) => e.data === 'Muted',
              target: 'Muted',
            },
            { target: 'Unmuted' },
          ],
        },
      },
      Muted: {
        entry: () => localStorage.setItem('volume-state', 'Muted'),
        on: {
          Toggle: {
            target: 'Unmuted',
          },
        },
      },
      Unmuted: {
        entry: () => localStorage.setItem('volume-state', 'Unmuted'),
        on: {
          Toggle: {
            target: 'Muted',
          },
        },
      },
    },
  },
}
```

With this change I would instead be able to do this
```js
Volume: {
    initial: () => localStorage.getItem("volume-state") ?? "Unmuted",
    states: {
      Muted: {
        entry: () => localStorage.setItem("volume-state", "Muted"),
        on: {
          Toggle: {
            target: "Unmuted",
          },
        },
      },
      Unmuted: {
        entry: () => localStorage.setItem("volume-state", "Unmuted"),
        on: {
          Toggle: {
            target: "Muted",
          },
        },
      },
    },
  },
```

It makes it easier and cleaner to be able to restore parts of a parallel state, but also for saving the state without having to save the complete state tree and restore it.

### CODE REVIEW

**Comment by Andarist** [comment]
I like the idea and I wish we had support for smth like this. But I think that a better direction would be to allow using conditional transitions for `initial`. This could have better support for our tooling (studio, typegen, etc) as it's easier to statically analyze those. I would have to recheck but I think that this might even be already implemented on the `next` branch (or there is at least some groundwork laid out for it there)

**Comment by davidkpiano** [comment]
> I like the idea and I wish we had support for smth like this. But I think that a better direction would be to allow using conditional transitions for `initial`. This could have better support for our tooling (studio, typegen, etc) as it's easier to statically analyze those. I would have to recheck but I think that this might even be already implemented on the `next` branch (or there is at least some groundwork laid out for it there)

Initial actions are, but not a conditional initial target. We could make an RFC for that idea because it's still viable, given that it is deterministic:

```js
initial: [
  { guard: 'something', target: 'first' },
  { target: 'second'
]
```

But with the original use-case, the more straightforward way to accomplish this is by persisting and restoring all state.

**Comment by danielbrodin** [comment]
> the more straightforward way to accomplish this is by persisting and restoring all state.

Well not really, because we can't restore all state. All states except one has to start from scratch. Your idea however would probably solve this as well since you could have a guard with `localStorage.getItem('volume-state') === 'Muted'`.

**Comment by Andarist** [comment]
I've created an internal ticket for v5 to work on this.

**Pull request closed without merging**
