### PR TITLE
Giving better type information for nextEvents

### PR DESCRIPTION
**Pull request by alexreardon**

### CODE REVIEW

**Comment by alexreardon** [comment]
It looks like this change falls over here:

```ts
const potentialEvents = flatten<TEvent>(
      nextEvents.map((nextEvent) => events[nextEvent] || [])
    ).map((event) => toEventObject(event));
```

It looks like my understanding of 'nextEvents' is shakey

**Comment by Andarist** [comment]
At first glance, the change looks OK - could you be more precise about what do you see failing with it?

**Comment by alexreardon** [comment]
```
Argument of type 'Record<TEvent["type"], Event<TEvent>[]>[TEvent["type"]][]' is not assignable to parameter of type '(TEvent | TEvent[])[]'.
  Type 'Event<TEvent>[]' is not assignable to type 'TEvent | TEvent[]'.
    Type 'Event<TEvent>[]' is not assignable to type 'TEvent[]'.
      Type 'Event<TEvent>' is not assignable to type 'TEvent'.
        Type 'TEvent["type"]' is not assignable to type 'TEvent'.
          Type 'string' is not assignable to type 'TEvent'.ts(2345)
```

**Comment by davidkpiano** [comment]
Superseded by #3447

**Pull request closed without merging**
