### PR TITLE
Fixed transition target resolving algorithm

### LINKED ISSUE #346: Root transitions are not working properly
Consider the following snippet:

```js
const wordMachine = Machine({
  id: 'direction',
  initial: 'left',
  states: {
    left: {},
    right: {},
    center: {},
    justify: {}
  },
  on: {
    LEFT_CLICK: 'left',
    RIGHT_CLICK: 'right',
    CENTER_CLICK: 'center',
    JUSTIFY_CLICK: 'justify'
  }
});
```

If you copy and paste it in the Visualizer (https://statecharts.github.io/xstate-viz/) you'll see that you can transition to `right` by clicking on `RIGHT_CLICK` event.

It shouldn't happen. `left` means "travel to my sibling left state", `direction` has no siblings.

The expected result would be a warning: `Target 'left' not found on 'direction'` (or something like that).

### PR DESCRIPTION
**Pull request by Andarist**
fixes #346

This is quite a breaking change though, so maybe shouldn't get merged in right away. Not sure what are the plans for the next major version.

### CODE REVIEW

**Comment by Andarist** [comment]
@davidkpiano would we like to revive this PR as part of v4? or should it wait for v5?

**Comment by davidkpiano** [comment]
Let's hold off on this until V5. We need to make sure we have a good resolution algorithm, and might want to support `"#foo.bar"` resolving to:

- `id: 'foo.bar'` if it exists...
- otherwise: `id: 'foo'` and find the child `'bar'` state

Not sure yet.

**Comment by davidkpiano** [comment]
Doing some cleanup, do we want to rework this for v5 instead?

**Comment by davidkpiano** [comment]
Superseded by https://github.com/statelyai/xstate/pull/2881

**Pull request closed without merging**
