### PR TITLE
docs: Typings for the context and the service

### PR DESCRIPTION
**Pull request by ilabacheuskicastor**
This PR will properly type the context.
With such way we could inform the users how to properly type our service, since right now it is not clear that we could use the generic `InterpreterFrom<>`

### CODE REVIEW

**Comment by mattpocock** [comment]
@davidkpiano @ilabacheuskicastor An extra TS example here feels a bit too verbose, we could just add:

`export const GlobalStateContext = createContext({} as InterpreterFrom<typeof authMachine>);`

to the existing example to make it fully TS compliant?

**Comment by mattpocock** [comment]
Or add it as a:

```
> For Typescript, you can type the context as `createContext({} as InterpreterFrom<typeof authMachine>);` to ensure you get proper autocomplete.
```

**Comment by davidkpiano** [comment]
> Or add it as a:
> 
> ```
> > For Typescript, you can create the context as `createContext({} as InterpreterFrom<typeof authMachine>);` to ensure strong typings.
> ```

From the two options, adding it as a note (like this) is sufficient

**Comment by ilabacheuskicastor** [comment]
@mattpocock @davidkpiano I will update

**Comment by ilabacheuskicastor** [comment]
LGTM, @mattpocock I had written the full example, bcs in my work I was unaware of the existing InterpreterFrom generic in the xstate. And Other generics was not very helpful :)

**Pull request merged**
