### PR TITLE
Add `model.createMachine(...)`

### PR DESCRIPTION
**Pull request by davidkpiano**
The model created from `createModel(...)` now provides a `.createMachine(...)` method that does not require passing any generic type parameters:

```diff
const model = createModel(/* ... */);

-const machine = createMachine<typeof model>(/* ... */);
+const machine = model.createMachine(/* ... */);
```

### CODE REVIEW

**Comment by mattpocock** [comment]
When you call `model.createMachine` without passing `context`, does it infer the context from the model? I'd expect that to happen.

**Comment by davidkpiano** [comment]
> When you call `model.createMachine` without passing `context`, does it infer the context from the model? I'd expect that to happen.

You mean the types or the actual value of the `initialContext`?

**Comment by mattpocock** [comment]
The actual value

**Comment by davidkpiano** [comment]
> The actual value

Added here: 6100fa085d7a3a20539adc91a5630db2eb7b934e

**Review by farskid — APPROVED** [review]

**Pull request merged**
